name: Scrape Email Security Headlines

on:
  schedule:
    - cron: "0 */6 * * *" 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Run scraper
        run: python code/scrape.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "[email protected]"
          git add results/
          git commit -m "🤖 Auto-update: Scraped news for $(date -u +"%Y-%m-%d %H:%M:%S") UTC" || echo "No changes to commit"
          git push